application: gaeswf
version: 1
runtime: python
api_version: 1

handlers:

# PyAMF Flash Remoting Gateway
- url: /gateway
  script: gateway.py    

# Static: Flash files.
- url: /swfs
  static_dir: swfs
    
# Static: JS files.
- url: /js
  static_dir: js    
  
# Static: CSS files
- url: /css
  static_dir: css
    
# Static: image files
- url: /images
  static_dir: images    

# Static: downloads
- url: /downloads
  static_dir: downloads
    
# Examples, each in the examples folder/name_of_example.
# Note: All examples share the same templates, flash, and js folders. 
#- url: /examples/(.*?)(/.*)?
#  script: examples/\1/main.py

# Everything else goes to the main app.
- url: /.*
  script: main.py
  
skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (swfs/org)|
 (swfs/.*?\.(css|html|fla|js|ttf))|
 (swfs/library.swf)|
 (swfs/misc.swf)|
 (swfs/yflexskin.swf)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (flash/.*)|
 ^(flex/.*)|
 (psd/.*)|
 (pyamf/tests/.*)|
 (tools/.*)|
 )$

