application: vypercms
version: 1
runtime: python
api_version: 1

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*\.bat)|
 (.*/RCS/.*)|
 (\..*)|
 (.*/\.svn/.*)|
 (.*/Thumbs\.db)|
 )$

default_expiration: '3650d'

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.py