application: uniqueificate
version: 1
api_version: 1
runtime: python

handlers:
- url: /static
  static_dir: static
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /(?!favicon.ico).*
  script: main.py


  